# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  config:
    import: optional:file:config.properties
  application:
    name: Employee-Management
  datasource:
    url: jdbc:postgresql://localhost:5432/EmployeeManagement
    username: postgres
    password: 3333
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # data:
  #   mongodb:
  #     uri: ${MONGO_URI}
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 8080

logging:
  level:
    org.springframework.security: WARN
